### ISSUE TITLE
Build fails with Python 3.12.3 and Cython 3.0.11

### ISSUE THREAD

**Issue by attie-argentum** [bryancole/raypier_optics#17]
I'm trying to build the latest public commit (d4985fee9637be493f476ba7b3c9a003e0282615), and the build fails, with Cython complaining in multiple locations:

- `Assignment of Python object not allowed without gil`
- `Compiler crash in AnalyseExpressionsTransform`

Unfortunately I don't know enough about Cython to help more.

```
(py3-venv) root@dac898a8285d:/opt/raypier# python3 ./setup.py build
Compiling raypier/core/cfields.pyx because it changed.
Compiling raypier/core/cimplicit_surfs.pyx because it changed.
Compiling raypier/core/cmaterials.pyx because it changed.
Compiling raypier/core/cshapes.pyx because it changed.
Compiling raypier/core/ctracer.pyx because it changed.
Compiling raypier/core/obbtree.pyx because it changed.
[1/6] Cythonizing raypier/core/cfields.pyx
warning: raypier/core/cfields.pyx:13:0: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
warning: raypier/core/ctracer.pxd:26:0: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
performance hint: raypier/core/cfields.pyx:118:5: Exception check on 'calc_mode_U' will always require the GIL to be acquired. Declare 'calc_mode_U' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: raypier/core/cfields.pyx:156:5: Exception check on 'evaluate_one_mode' will always require the GIL to be acquired.
Possible solutions:
        1. Declare 'evaluate_one_mode' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
        2. Use an 'int' return type on 'evaluate_one_mode' to allow an error code to be returned.

Error compiling Cython file:
------------------------------------------------------------
...
        a22 += yi2*yi2
        b0 += xi2
        b1 += 2*x[i]*y[i]
        b2 += yi2

    out[0].imag = blending *(-b0*(a11*a22 - a12**2) + b1*(a01*a22 - a02*a12) - b2*(a01*a12 - a02*a11))/(-a00*a11*a22 + a00*a12**2 + a01**2*a22 - 2*a01*a02*a12 + a02**2*a11)
          ^
------------------------------------------------------------

raypier/core/cfields.pyx:182:10: Assignment of Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        b0 += xi2
        b1 += 2*x[i]*y[i]
        b2 += yi2

    out[0].imag = blending *(-b0*(a11*a22 - a12**2) + b1*(a01*a22 - a02*a12) - b2*(a01*a12 - a02*a11))/(-a00*a11*a22 + a00*a12**2 + a01**2*a22 - 2*a01*a02*a12 + a02**2*a11)
    out[1].imag = -blending *(b0*(a01*a22 - a02*a12) - b1*(a00*a22 - a02**2) + b2*(a00*a12 - a01*a02))/(-a00*a11*a22 + a00*a12**2 + a01**2*a22 - 2*a01*a02*a12 + a02**2*a11)
          ^
------------------------------------------------------------

raypier/core/cfields.pyx:183:10: Assignment of Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        b1 += 2*x[i]*y[i]
        b2 += yi2

    out[0].imag = blending *(-b0*(a11*a22 - a12**2) + b1*(a01*a22 - a02*a12) - b2*(a01*a12 - a02*a11))/(-a00*a11*a22 + a00*a12**2 + a01**2*a22 - 2*a01*a02*a12 + a02**2*a11)
    out[1].imag = -blending *(b0*(a01*a22 - a02*a12) - b1*(a00*a22 - a02**2) + b2*(a00*a12 - a01*a02))/(-a00*a11*a22 + a00*a12**2 + a01**2*a22 - 2*a01*a02*a12 + a02**2*a11)
    out[2].imag = blending *(-b0*(a01*a12 - a02*a11) + b1*(a00*a12 - a01*a02) - b2*(a00*a11 - a01**2))/(-a00*a11*a22 + a00*a12**2 + a01**2*a22 - 2*a01*a02*a12 + a02**2*a11)
          ^
------------------------------------------------------------

raypier/core/cfields.pyx:184:10: Assignment of Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        b1 += dx[i]*y[i] + dy[i]*x[i]
        b2 += dy[i]*y[i]

    a12 = a01*a01 #reuse a12 as an optimisation

    out[0].real = (-a12*b2 + a01*a22*b1 + b0*(a12 - a11*a22))/(a00*a12 - a00*a11*a22 + a12*a22)
          ^
------------------------------------------------------------

raypier/core/cfields.pyx:211:10: Assignment of Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        b2 += dy[i]*y[i]

    a12 = a01*a01 #reuse a12 as an optimisation

    out[0].real = (-a12*b2 + a01*a22*b1 + b0*(a12 - a11*a22))/(a00*a12 - a00*a11*a22 + a12*a22)
    out[1].real = -(a00*a01*b2 - a00*a22*b1 + a01*a22*b0)/(a00*a12 - a00*a11*a22 + a12*a22)
          ^
------------------------------------------------------------

raypier/core/cfields.pyx:212:10: Assignment of Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...

    a12 = a01*a01 #reuse a12 as an optimisation

    out[0].real = (-a12*b2 + a01*a22*b1 + b0*(a12 - a11*a22))/(a00*a12 - a00*a11*a22 + a12*a22)
    out[1].real = -(a00*a01*b2 - a00*a22*b1 + a01*a22*b0)/(a00*a12 - a00*a11*a22 + a12*a22)
    out[2].real = (a00*a01*b1 - a12*b0 - b2*(a00*a11 - a12))/(a00*a12 - a00*a11*a22 + a12*a22)
          ^
------------------------------------------------------------

raypier/core/cfields.pyx:213:10: Assignment of Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...

def evaluate_modes(double[:,:] x, double[:,:] y, double[:,:] dx, double[:,:] dy, double blending=1.0):
    cdef:
        int n_rays=x.shape[0], row_size=x.shape[1]
        int i
        np_.npy_complex128[:,:] out = np.zeros((n_rays,3), dtype=np.complex128)
                                              ^
------------------------------------------------------------

raypier/core/cfields.pyx:222:46: Compiler crash in AnalyseExpressionsTransform

ModuleNode.body = StatListNode(cfields.pyx:2:0)
StatListNode.stats[12] = StatListNode(cfields.pyx:218:0)
StatListNode.stats[0] = DefNode(cfields.pyx:218:0,
    is_cyfunction = True,
    modifiers = [...]/0,
    name = 'evaluate_modes',
    np_args_idx = [...]/0,
    num_required_args = 4,
    outer_attrs = [...]/2,
    py_wrapper_required = True,
    reqd_kw_flags_cname = '0',
    used = True)
File 'Nodes.py', line 397, in analyse_expressions: StatListNode(cfields.pyx:219:4,
    is_terminator = True)
File 'Nodes.py', line 397, in analyse_expressions: StatListNode(cfields.pyx:220:8)
File 'Nodes.py', line 6056, in analyse_expressions: SingleAssignmentNode(cfields.pyx:222:8,
    first = True)
File 'Nodes.py', line 6222, in analyse_types: SingleAssignmentNode(cfields.pyx:222:8,
    first = True)
File 'ExprNodes.py', line 1021, in coerce_to: GeneralCallNode(cfields.pyx:222:46,
    is_temp = 1,
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 13820, in __init__: CoerceToMemViewSliceNode(cfields.pyx:222:46,
    is_temp = 1,
    result_is_used = True,
    use_managed_ref = True)

Compiler crash traceback from this point on:
  File "/opt/py3-venv/lib/python3.12/site-packages/Cython/Compiler/ExprNodes.py", line 13820, in __init__
    self.type.create_from_py_utility_code(env)
  File "/opt/py3-venv/lib/python3.12/site-packages/Cython/Compiler/PyrexTypes.py", line 1002, in create_from_py_utility_code
    struct_nesting_depth = self.dtype.struct_nesting_depth(),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3-venv/lib/python3.12/site-packages/Cython/Compiler/PyrexTypes.py", line 3940, in struct_nesting_depth
    return max(child_depths) + 1
           ^^^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty
Traceback (most recent call last):
  File "/opt/raypier/./setup.py", line 37, in <module>
    ext_modules = cythonize("raypier/core/*.pyx",
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3-venv/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "/opt/py3-venv/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: raypier/core/cfields.pyx
```

```
(py3-venv) root@dac898a8285d:/opt/raypier# python3 --version
Python 3.12.3
```

```
(py3-venv) root@dac898a8285d:/opt/raypier# pip freeze
contourpy==1.3.0
cycler==0.12.1
Cython==3.0.11
fonttools==4.53.1
kiwisolver==1.4.7
matplotlib==3.9.2
numpy==2.1.1
packaging==24.1
pillow==10.4.0
pyparsing==3.1.4
python-dateutil==2.9.0.post0
scipy==1.14.1
setuptools==74.1.1
six==1.16.0
vtk==9.3.1
```

**Comment by bryancole** [comment]
Just pushed a changeset on master. This fixes the Cython errors with Cython>=3. The project now seems to build fine.

The catch is that I can't get Enable to build on py3.12/Cython3. The Enable requirements specify Cython<3. When I downgrade Cython, I get much the same error. This may be a py3.12 issue with Enable rather than a Cython one.

Without Enable, then Chaco won't work. Hence, no line-plots or image-plots. If you already have a version of Enable built/installed you don't need to worry but it's annoying not being able to pip-install it.

A second problem is that pyximport (part of Cython) doesn't seem to work on py3.12, due to the imp module being depreciated. However, pyximport is not really necessary to run Raypier. I have pyximport in a few places as a convenience in development (it auto-builds the Cython modules if the code changes). I think you can simply comment these out. 

I was able to get the bessel-beam example to run but commenting out the IntensityImageView (which uses Chaco) and removing a couple of pyximport lines in dispersions.py.

**Comment by attie-argentum** [comment]
Many thanks for your prompt work! I'll see if I can try again soon - for the moment I've managed to get by using a much simpler project.

**Comment by ElliotB256** [comment]
Commenting to say I'm also experiencing the original error on python 3.8 / cython 3.0.10 when pip installing. It's a shame not being able to pip install the dependency, I've stuck with an earlier installed version for now.

**Comment by bryancole** [comment]
I've been working on building Raypier on Windows. It seems one needs to set the requirements as:
- cython<3
- numpy<2

Chaco and its dependencies continues to be a nightmare to get installed. I've decided to remove Chaco as a dependency. I'm planning to re-write the things which need Chaco (image-plot and line-plot widgets) to use the VTK charting components instead. The catch is that integrating the VTK widgets into a traitsui application needs quite a lot of work (the usual mayavi VTK 3D scene won't work). Sigh...
